### ISSUE TITLE
struggling to build 

### ISSUE THREAD

**Issue by venkatbaytech** [repk/epd#1]
I tried to build with Raspberry pi with kernel 3.18.0-trunk-rpi. This version have issue with device tree. So I downgraded to 3.12-1.rpi. In make file I am not able to build.

Please let me know the build environment you used for this projec

**Comment by repk** [comment]
Hi,

I have built this driver with the rpi-4.1.y branch (the default one) from https://github.com/raspberrypi/linux.

Please let me know if you have problem with this version.

**Comment by venkatbaytech** [comment]
I built it working in PI.
Now porting this to BBB. Any suggestion for that is welcome. And trying to upgrade to G2 class EPD. Once done will share it. Before that, have you done those changes?
venkat

**Comment by repk** [comment]
That is very good news.

Porting to BBB will be a matter of selecting the appropriate GPIOs in device tree I guess. Please let me know if modifying the device tree is not enough.
I have, just recently, been back onto G2 support. I'll make the development branch available, if you want to test it, as soon as I have something that looks ok.

Remi

**Comment by venkatbaytech** [comment]
Thank you for your reply. We try to implement the BBB setup. once it is
done, will let you know.

regards
venkat

**Comment by venkatbaytech** [comment]
Hi,

I just your module. struck with the usage modstub-test folder. You have
core.c in that folder also. May I know the purpose of this core.c and
overall what is the use of modstub-test folder codes.

I am trying to port this in BBB over android os. May I get any help on this.

regards,
venkat

**Comment by repk** [comment]
modstub-test folder was here to test and debug the module in userland. You can skip it.

Unfortunaltely I have no BBB and I do not know much about android, but as this is a kernel module I would expect that using this is only a matter of writing the appropriate device tree.

Remi
